//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCodeGenerate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Interview()
        {
            this.InterviewDetail = new HashSet<InterviewDetail>();
        }
    
        public long Id { get; set; }
        public string IP { get; set; }
        public string UserAgent { get; set; }
        public string OperatingSystem { get; set; }
        public string BrowserType { get; set; }
        public System.DateTime ViewTime { get; set; }
        public string FromUrl { get; set; }
        public string Province { get; set; }
        public string ISP { get; set; }
        public string HttpMethod { get; set; }
        public string Address { get; set; }
        public string ReferenceAddress { get; set; }
        public string LandPage { get; set; }
        public string OnlineSpan { get; set; }
        public System.Guid Uid { get; set; }
        public double OnlineSpanSeconds { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterviewDetail> InterviewDetail { get; set; }
    }
}
