//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCodeGenerate
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginRecord
    {
        public int Id { get; set; }
        public string IP { get; set; }
        public System.DateTime LoginTime { get; set; }
        public string PhysicAddress { get; set; }
        public int LoginType { get; set; }
        public int UserInfoId { get; set; }
        public int Status { get; set; }
        public string Province { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
