//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCodeGenerate
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostHistoryVersion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostHistoryVersion()
        {
            this.Seminar = new HashSet<Seminar>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int ViewCount { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int CategoryId { get; set; }
        public int PostId { get; set; }
        public string ResourceName { get; set; }
        public bool IsWordDocument { get; set; }
        public string Email { get; set; }
        public string Label { get; set; }
        public int VoteUpCount { get; set; }
        public int VoteDownCount { get; set; }
        public int Status { get; set; }
        public string ProtectContent { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Post Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seminar> Seminar { get; set; }
    }
}
